target:
  type: teradata
  server: "{{ env_var('DBT_TERADATA_SERVER_NAME', 'localhost') }}"
  username: "{{ env_var('DBT_TERADATA_USERNAME', 'dbc') }}"
  password: "{{ env_var('DBT_TERADATA_PASSWORD', 'dbc') }}"
  schema: "dbt_test_{{ var('_dbt_random_suffix') }}"
  tmode: ANSI
  log: "0"

projects:
  - name: project_for_test
    paths:
      dbt_project.yml: |
        name: 'project_for_test'
        version: '1.0.0'
        config-version: 2
        dispatch:
          - macro_namespace: dbt_utils
            search_order:
              - teradata_utils
              - dbt_utils

      packages.yml: |
        packages:
        - package: dbt-labs/dbt_utils
          version: 1.1.1
        - local: "{{ env_var('DBT_TERADATA_UTILS_ROOT') }}"

      models/report.sql: |
        {{
          config(
            materialized="table"
          )
        }}
        -- this is just to test that log_info macro does not error out
        {{ dbt_utils.log_info("my pretty message") }}
        SELECT current_timestamp as _timestamp

sequences:
  test:
    project: project_for_test
    sequence:
      - type: dbt
        cmd: deps
      - type: dbt
        cmd: run
      - type: run_results
        exists: True
        names:
          - report
      - type: relation_rows
        name: report
        length: 1
